on:
  push:
    branches: [ "main" ]

jobs:
  ios-build:
    name: iOS Dev Build
    runs-on: self-hosted
    steps:
      - name: Show self-hosted machine information
        run: uname -a

      - name: Cancel previous runs
        uses: styfle/cancel-workflow-action@0.9.1

      - name: Checkout repo from main branch
        uses: actions/checkout@v3

      - name: Install npm dependencies
        run: yarn install

      - name: Cache cocoapods
        uses: actions/cache@v3
        with:
          path: ios/Pods
          key: ${{ runner.os }}-pods-${{ hashFiles('**/Podfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-pods-

      - name: Install pod dependencies
        run: |
          cd ios
          bundle exec pod install

      - name: Build iOS JS Bundle
        run: yarn run package-ios

      - name: Install bundler
        run: |
          cd ios
          gem install bundler

      - name: Install gem plugins
        run: |
          cd ios
          bundle install

      - name: Run iOS build process
        run: |
          cd ios
          echo "Replace this with actual iOS build command if Fastlane is not used"

  android-build:
    name: Android Dev Build
    runs-on: self-hosted
    steps:
      - name: Show self-hosted machine information
        run: uname -a

      - name: Cancel previous runs
        uses: styfle/cancel-workflow-action@0.9.1

      - name: Checkout repo from main branch
        uses: actions/checkout@v3

      - name: Install npm dependencies
        run: yarn install

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2

      - name: Cache Gradle
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Execute Gradle build
        run: |
          cd android
          ./gradlew build

      - name: Build Android JS Bundle
        run: yarn run package-android

      - name: Delete Android build duplicate assets resource
        run: yarn run delete-pics

      - name: Install bundler
        run: |
          cd android
          gem install bundler

      - name: Install gem plugins
        run: |
          cd android
          bundle install

      - name: Run Android build process
        run: |
          cd android
          echo "Replace this with actual Android build command if Fastlane is not used"
